import { z } from "zod";
import { ActorTypeSchema } from "./event.js";
import { RiskLevelSchema } from "./policy.js";
import { SensitivityLevelSchema } from "./security.js";

/**
 * Metadata specification describing what a tool does and its execution properties.
 * PRD Part 1 Section 83 & PRD Part 2 Section 41.
 */
export const ToolSpecSchema = z.object({
  name: z.string().min(1),
  description: z.string().optional(),
  parametersSchema: z.record(z.unknown()),
  outputSchema: z.record(z.unknown()).optional(),
  riskLevel: RiskLevelSchema.optional(),
  requiredCapabilities: z.array(z.string()).optional(),
  timeoutMs: z.number().int().positive().optional(),
  isIdempotent: z.boolean().default(false),
  requiresApproval: z.boolean().optional(),
  sensitivity: SensitivityLevelSchema.optional(),
});
export type ToolSpec = z.infer<typeof ToolSpecSchema>;

export const ToolMetadataSchema = ToolSpecSchema;
export type ToolMetadata = ToolSpec;

/**
 * Invocation request sent to the ToolGateway.
 */
export const ToolInvocationRequestSchema = z.object({
  callId: z.string().min(1),
  toolName: z.string().min(1),
  arguments: z.record(z.unknown()).default({}),
  actor: z.object({
    id: z.string().min(1),
    type: ActorTypeSchema,
    role: z.string().optional(),
  }),
  project: z.object({
    id: z.string().min(1),
  }),
  session: z.object({ id: z.string() }).optional(),
  task: z.object({ id: z.string() }).optional(),
  approvalId: z.string().optional(),
  idempotencyKey: z.string().optional(),
  timeoutMs: z.number().int().positive().optional(),
});
export type ToolInvocationRequest = z.infer<typeof ToolInvocationRequestSchema>;

/**
 * Execution status classification for tool observations.
 */
export const ToolExecutionStatusSchema = z.enum([
  "success",
  "failure",
  "approval_required",
  "denied",
  "timeout",
  "cancelled",
]);
export type ToolExecutionStatus = z.infer<typeof ToolExecutionStatusSchema>;

/**
 * Error record generated by failed or rejected tool execution.
 */
export const ToolExecutionErrorSchema = z.object({
  code: z.string().min(1),
  message: z.string().min(1),
  retryable: z.boolean(),
  details: z.unknown().optional(),
});
export type ToolExecutionError = z.infer<typeof ToolExecutionErrorSchema>;

/**
 * Authoritative Observation returned by the ToolGateway.
 * PRD Part 1 Section 85 & PRD Part 2 Section 42.
 */
export const ToolObservationSchema = z.object({
  callId: z.string().min(1),
  toolName: z.string().min(1),
  status: ToolExecutionStatusSchema,
  result: z.unknown().optional(),
  error: ToolExecutionErrorSchema.optional(),
  durationMs: z.number().nonnegative(),
  executedAt: z.string().min(1),
  idempotencyKey: z.string().optional(),
  fromCache: z.boolean().optional(),
  approvalId: z.string().optional(),
  artifactRef: z.string().optional(),
  provenanceId: z.string().optional(),
});
export type ToolObservation = z.infer<typeof ToolObservationSchema>;
